/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModeloGrafico;

import Clases.Conexion;
import Clases.Producto;
import Clases.Usuario;
import Clases.Venta;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class PreVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu2
     */
    public Usuario per;
    public PreVenta() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_MsgWelcome = new javax.swing.JLabel();
        jLabel_MsgStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        jTextField_Folio = new javax.swing.JTextField();
        jTextField_Vendedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_compra = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_preciototal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_busqueda = new javax.swing.JTable();
        jTextField_BCodigo = new javax.swing.JTextField();
        jTextField_Bnombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton_BuscarPorCodigo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton_BuscarPorNombre = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton_AgregarAlCarro = new javax.swing.JButton();
        jTextField_CantProd = new javax.swing.JFormattedTextField();
        jButton_Salir = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel_MsgWelcome.setText("Welcome X");

        jLabel_MsgStatus.setText("STATUS");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("FOLIO:");

        jTextField_Fecha.setEditable(false);

        jLabel_fecha.setText("FECHA");

        jTextField_Folio.setEditable(false);

        jTextField_Vendedor.setEditable(false);

        jLabel4.setText("VENDEDOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Folio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel_fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_fecha)
                    .addComponent(jTextField_Folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_compra);

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("TOTAL");

        jTextField_preciototal.setEditable(false);
        jTextField_preciototal.setText("0");

        jButton2.setText("Efectuar Compra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_preciototal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_preciototal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable_busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripción", "Categoría", "Composición", "Stock", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_busqueda);

        jTextField_Bnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_BnombreActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingrese código");

        jButton_BuscarPorCodigo.setText("Buscar");
        jButton_BuscarPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarPorCodigoActionPerformed(evt);
            }
        });

        jLabel7.setText("Ingrese nombre");

        jButton_BuscarPorNombre.setText("Buscar");
        jButton_BuscarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarPorNombreActionPerformed(evt);
            }
        });

        jLabel8.setText("Cantidad");

        jButton_AgregarAlCarro.setText("Añadir");
        jButton_AgregarAlCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AgregarAlCarroMouseClicked(evt);
            }
        });
        jButton_AgregarAlCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarAlCarroActionPerformed(evt);
            }
        });

        jTextField_CantProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_BCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_BuscarPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Bnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButton_BuscarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_CantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_AgregarAlCarro)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_BCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Bnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton_BuscarPorCodigo)
                    .addComponent(jLabel7)
                    .addComponent(jButton_BuscarPorNombre))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton_AgregarAlCarro)
                    .addComponent(jTextField_CantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton_Salir.setText("Cerrar Sesion");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_MsgWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_MsgStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jButton_Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MsgWelcome)
                    .addComponent(jLabel_MsgStatus)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        jTextField_Vendedor.setText(per.getNombre());
        jLabel_MsgWelcome.setText("Bienvenido "+per.getNombre());
        jTextField_CantProd.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                    char c = e.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
        CargarNuevaCompra();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton_AgregarAlCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AgregarAlCarroMouseClicked
       
    }//GEN-LAST:event_jButton_AgregarAlCarroMouseClicked

    private void jButton_AgregarAlCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarAlCarroActionPerformed
        // TODO add your handling code here:
        if(jTable_busqueda.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            AgregarAlCarro();
            jTextField_CantProd.setText("");           
        }
        
    }//GEN-LAST:event_jButton_AgregarAlCarroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int fila = jTable_compra.getSelectedRow();
        int total = Integer.parseInt(jTextField_preciototal.getText().trim());
        int valor = Integer.parseInt(jTable_compra.getValueAt(fila, 3).toString());
        int subtotal = total - valor;
        jTextField_preciototal.setText(String.valueOf(subtotal));
        ((DefaultTableModel)jTable_compra.getModel()).removeRow(jTable_compra.getSelectedRow());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_BuscarPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarPorCodigoActionPerformed
        // TODO add your handling code here:
        Conexion c = new Conexion();
        Producto prod = c.retorna_producto(jTextField_BCodigo.getText());
        if(prod == null) {
            JOptionPane.showMessageDialog(this, "No hay productos con estos datos", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            Object[] row = { prod.getCodigo(), prod.getNombre(), prod.getDescripcion(), prod.getCategoria(), prod.getComponente(), prod.getStock(), prod.getPrecio() };
            DefaultTableModel modelbusqueda = (DefaultTableModel) jTable_busqueda.getModel();
            if(modelbusqueda.getRowCount() >= 1) {
                modelbusqueda.removeRow(0);
            }       
            modelbusqueda.addRow(row);
            jTable_busqueda.setModel(modelbusqueda);
        }
        c.cerrar();
    }//GEN-LAST:event_jButton_BuscarPorCodigoActionPerformed

    private void jButton_BuscarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarPorNombreActionPerformed
        Conexion c = new Conexion();
        Producto prod = c.retorna_producto_n(jTextField_Bnombre.getText());
        if(prod == null) {
            JOptionPane.showMessageDialog(this, "No hay productos con estos datos", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            Object[] row = { prod.getCodigo(), prod.getNombre(), prod.getDescripcion(), prod.getCategoria(), prod.getComponente(), prod.getStock(), prod.getPrecio() };
            DefaultTableModel modelbusqueda = (DefaultTableModel) jTable_busqueda.getModel();
            if(modelbusqueda.getRowCount() >= 1) {
                modelbusqueda.removeRow(0);
            } 
            modelbusqueda.addRow(row);
            jTable_busqueda.setModel(modelbusqueda);
        }
        c.cerrar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BuscarPorNombreActionPerformed

    private void jTextField_BnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BnombreActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Main.IniciarVentanaLogin();
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel modelcompra = (DefaultTableModel) jTable_compra.getModel();      
        int col=modelcompra.getRowCount();
        
        Conexion c = new Conexion();
        int f=Integer.parseInt(jTextField_Folio.getText())+1;
        String fec=jTextField_Fecha.getText();
        String ve=jTextField_Vendedor.getText();
        int to= Integer.parseInt(jTextField_preciototal.getText());
        Venta v = new Venta (f,fec,ve,to);
        c.crear_venta(v);
        int cant;
        int total;
        String nombre;
        String codigo;
        
        for(int i=0; i<col;i++)
            {
                codigo = String.valueOf(modelcompra.getValueAt(i, 0));
                nombre = String.valueOf(modelcompra.getValueAt(i, 1));
                cant = Integer.parseInt(String.valueOf(modelcompra.getValueAt(i, 2)));
                total = Integer.parseInt(String.valueOf(modelcompra.getValueAt(i, 3)));
                Producto p = new Producto(codigo, nombre, total, cant);
                v.detalle.add(p);
                               
            }
        c.crear_detalle(v.detalle,f);
        JOptionPane.showMessageDialog(this, "Su compra ha sido realizada con exito");
        jTextField_Folio.setText(String.valueOf(f));
        jTextField_preciototal.setText("0");
        LimpiarTablas();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void CargarUsuario(Usuario u) {
        per = u;
    }

    private void CargarNuevaCompra() {
        Conexion c = new Conexion();
        LocalDateTime fecha = LocalDateTime.now();
        String fechacompleta = Integer.toString(fecha.getDayOfMonth()) + "/" + Integer.toString(fecha.getMonthValue()) + "/" + Integer.toString(fecha.getYear());
        jTextField_Fecha.setText(fechacompleta);
        jTextField_Folio.setText(String.valueOf(c.getUltimoFolio()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_AgregarAlCarro;
    private javax.swing.JButton jButton_BuscarPorCodigo;
    private javax.swing.JButton jButton_BuscarPorNombre;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_MsgStatus;
    public static javax.swing.JLabel jLabel_MsgWelcome;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_busqueda;
    private javax.swing.JTable jTable_compra;
    private javax.swing.JTextField jTextField_BCodigo;
    private javax.swing.JTextField jTextField_Bnombre;
    private javax.swing.JFormattedTextField jTextField_CantProd;
    private javax.swing.JTextField jTextField_Fecha;
    private javax.swing.JTextField jTextField_Folio;
    public static javax.swing.JTextField jTextField_Vendedor;
    private javax.swing.JTextField jTextField_preciototal;
    // End of variables declaration//GEN-END:variables

    private void AgregarAlCarro() {
        if(jTextField_CantProd.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Coloque la cant de productos", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            int fila = jTable_busqueda.getSelectedRow();
            Object data = jTable_busqueda.getValueAt(fila, 5);
            if(Integer.parseInt(data.toString()) < Integer.parseInt(jTextField_CantProd.getText())) {
                JOptionPane.showMessageDialog(this, "No puedes añadir mas de lo que hay", "ERROR", JOptionPane.WARNING_MESSAGE);
            } else {
                int filasc = jTable_compra.getModel().getRowCount();
                boolean existeproducto = false;
                if(filasc >= 1) {
                    for(int i = 0; i < filasc; i++) {
                        Object code = jTable_compra.getValueAt(i, 0);
                        if(code.toString().equalsIgnoreCase(jTable_busqueda.getValueAt(fila, 0).toString())) {
                            existeproducto = true;
                        }
                    }
                }
                
                if(existeproducto) {
                    JOptionPane.showMessageDialog(this, "Ya existe el producto en el carro de compra", "ERROR", JOptionPane.WARNING_MESSAGE);
                } else {
                    Object[] row = { jTable_busqueda.getValueAt(fila, 0), jTable_busqueda.getValueAt(fila, 1), jTextField_CantProd.getText(), Integer.parseInt(jTable_busqueda.getValueAt(fila, 6).toString()) * Integer.parseInt(jTextField_CantProd.getText())};
                    DefaultTableModel modelcompra = (DefaultTableModel) jTable_compra.getModel();
                    modelcompra.addRow(row);
                    jTable_compra.setModel(modelcompra);
                    int total = Integer.parseInt(jTextField_preciototal.getText().trim());
                    int valor = Integer.parseInt(jTable_busqueda.getValueAt(fila, 6).toString()) * Integer.parseInt(jTextField_CantProd.getText());
                    int subtotal = total + valor;
                    jTextField_preciototal.setText(String.valueOf(subtotal));
                    ((DefaultTableModel)jTable_busqueda.getModel()).removeRow(0);
                }
            }
        }
    }

    private void LimpiarTablas() {
        int datos_busqueda = jTable_busqueda.getRowCount();
        int datos_comprar = jTable_compra.getRowCount();
        
        if(datos_busqueda > 0) {
            for(int x = 0; x < datos_busqueda; x++) {
                ((DefaultTableModel)jTable_busqueda.getModel()).removeRow(x);
            }
        }
        if(datos_comprar > 0) {
            for(int x = 0; x < datos_comprar; x++) {
                ((DefaultTableModel)jTable_compra.getModel()).removeRow(x);
            }
        }
    }
  
}
